// Mock data for development/demo purposes
export const mockPosts = [
  {
    id: '1',
    title: 'Getting Started with React CMS',
    slug: 'getting-started-react-cms',
    content: '<p>This is a comprehensive guide to using our React CMS system...</p>',
    excerpt: 'Learn how to use our React CMS system effectively',
    status: 'published',
    type: 'post',
    featured_image_url: '/images/blog/blog-01.jpg',
    seo: {
      meta_title: 'Getting Started with React CMS - Guide',
      meta_description: 'Complete guide to using React CMS for content management',
      meta_keywords: 'react, cms, tutorial, guide',
    },
    author_id: '1',
    created_at: '2024-01-15T10:00:00Z',
    updated_at: '2024-01-15T10:00:00Z',
    published_at: '2024-01-15T10:00:00Z',
    categories: [{ id: '1', name: 'Tutorial', slug: 'tutorial' }],
    tags: [
      { id: '1', name: 'React', slug: 'react' },
      { id: '2', name: 'CMS', slug: 'cms' },
    ],
  },
  {
    id: '2',
    title: 'Advanced Media Management',
    slug: 'advanced-media-management',
    content: '<p>Learn advanced techniques for managing media in your CMS...</p>',
    excerpt: 'Advanced techniques for media management',
    status: 'draft',
    type: 'post',
    featured_image_url: '/images/blog/blog-02.jpg',
    seo: {
      meta_title: 'Advanced Media Management Tips',
      meta_description: 'Professional tips for managing media content',
      meta_keywords: 'media, management, cms, tips',
    },
    author_id: '1',
    created_at: '2024-01-16T14:30:00Z',
    updated_at: '2024-01-16T14:30:00Z',
    published_at: null,
    categories: [{ id: '2', name: 'Tips', slug: 'tips' }],
    tags: [
      { id: '3', name: 'Media', slug: 'media' },
      { id: '4', name: 'Advanced', slug: 'advanced' },
    ],
  },
  {
    id: '3',
    title: 'Multi-tenant Architecture',
    slug: 'multi-tenant-architecture',
    content: '<p>Understanding multi-tenant architecture in modern CMS systems...</p>',
    excerpt: 'Deep dive into multi-tenant CMS architecture',
    status: 'published',
    type: 'post',
    featured_image_url: '/images/blog/blog-03.jpg',
    seo: {
      meta_title: 'Multi-tenant CMS Architecture Explained',
      meta_description: 'Complete guide to multi-tenant CMS architecture',
      meta_keywords: 'multi-tenant, architecture, cms, scalability',
    },
    author_id: '2',
    created_at: '2024-01-17T09:15:00Z',
    updated_at: '2024-01-17T09:15:00Z',
    published_at: '2024-01-17T09:15:00Z',
    categories: [{ id: '3', name: 'Architecture', slug: 'architecture' }],
    tags: [
      { id: '5', name: 'Architecture', slug: 'architecture' },
      { id: '6', name: 'Scalability', slug: 'scalability' },
    ],
  },
];

export const mockMedia = [
  {
    id: '1',
    filename: 'hero-image.jpg',
    original_filename: 'hero-image.jpg',
    url: '/images/grid-image/grid-01.jpg',
    thumbnail_url: '/images/grid-image/grid-01.jpg',
    file_size: 245760,
    mime_type: 'image/jpeg',
    width: 1200,
    height: 800,
    alt_text: 'Hero image for homepage',
    title: 'Beautiful landscape',
    caption: 'A stunning landscape photograph',
    description: 'High resolution landscape photo perfect for hero sections',
    created_at: '2024-01-15T08:00:00Z',
    updated_at: '2024-01-15T08:00:00Z',
  },
  {
    id: '2',
    filename: 'product-showcase.jpg',
    original_filename: 'product-showcase.jpg',
    url: '/images/grid-image/grid-02.jpg',
    thumbnail_url: '/images/grid-image/grid-02.jpg',
    file_size: 189440,
    mime_type: 'image/jpeg',
    width: 800,
    height: 600,
    alt_text: 'Product showcase image',
    title: 'Product display',
    caption: 'Professional product photography',
    description: 'Clean product showcase for e-commerce',
    created_at: '2024-01-16T10:30:00Z',
    updated_at: '2024-01-16T10:30:00Z',
  },
  {
    id: '3',
    filename: 'team-photo.jpg',
    original_filename: 'team-photo.jpg',
    url: '/images/grid-image/grid-03.jpg',
    thumbnail_url: '/images/grid-image/grid-03.jpg',
    file_size: 312480,
    mime_type: 'image/jpeg',
    width: 1000,
    height: 667,
    alt_text: 'Team photo',
    title: 'Our amazing team',
    caption: 'The team behind the success',
    description: 'Professional team photograph for about page',
    created_at: '2024-01-17T14:20:00Z',
    updated_at: '2024-01-17T14:20:00Z',
  },
];

export const mockCategories = [
  {
    id: '1',
    name: 'Tutorial',
    slug: 'tutorial',
    type: 'category',
    parent_id: null,
    description: 'Step-by-step tutorials and guides',
    created_at: '2024-01-10T00:00:00Z',
    posts_count: 5,
  },
  {
    id: '2',
    name: 'Tips',
    slug: 'tips',
    type: 'category',
    parent_id: null,
    description: 'Quick tips and tricks',
    created_at: '2024-01-10T00:00:00Z',
    posts_count: 3,
  },
  {
    id: '3',
    name: 'Architecture',
    slug: 'architecture',
    type: 'category',
    parent_id: null,
    description: 'System architecture and design patterns',
    created_at: '2024-01-10T00:00:00Z',
    posts_count: 2,
  },
  {
    id: '4',
    name: 'Frontend',
    slug: 'frontend',
    type: 'category',
    parent_id: '1',
    description: 'Frontend development tutorials',
    created_at: '2024-01-10T00:00:00Z',
    posts_count: 8,
  },
];

export const mockTags = [
  {
    id: '1',
    name: 'React',
    slug: 'react',
    type: 'tag',
    parent_id: null,
    description: 'React.js related content',
    created_at: '2024-01-10T00:00:00Z',
    posts_count: 12,
  },
  {
    id: '2',
    name: 'CMS',
    slug: 'cms',
    type: 'tag',
    parent_id: null,
    description: 'Content Management System',
    created_at: '2024-01-10T00:00:00Z',
    posts_count: 6,
  },
  {
    id: '3',
    name: 'Media',
    slug: 'media',
    type: 'tag',
    parent_id: null,
    description: 'Media management and optimization',
    created_at: '2024-01-10T00:00:00Z',
    posts_count: 4,
  },
  {
    id: '4',
    name: 'Advanced',
    slug: 'advanced',
    type: 'tag',
    parent_id: null,
    description: 'Advanced techniques and methods',
    created_at: '2024-01-10T00:00:00Z',
    posts_count: 3,
  },
];

export const mockComments = [
  {
    id: '1',
    post_id: '1',
    parent_id: null,
    author_name: 'John Doe',
    author_email: 'john@example.com',
    author_url: 'https://johndoe.com',
    content: 'Great tutorial! This really helped me understand the CMS system better.',
    status: 'approved',
    created_at: '2024-01-16T10:30:00Z',
    updated_at: '2024-01-16T10:30:00Z',
    post: {
      id: '1',
      title: 'Getting Started with React CMS',
      slug: 'getting-started-react-cms',
    },
    replies: [],
    replies_count: 0,
  },
  {
    id: '2',
    post_id: '1',
    parent_id: null,
    author_name: 'Jane Smith',
    author_email: 'jane@example.com',
    author_url: null,
    content: 'Could you add more examples about the media management part?',
    status: 'pending',
    created_at: '2024-01-17T08:15:00Z',
    updated_at: '2024-01-17T08:15:00Z',
    post: {
      id: '1',
      title: 'Getting Started with React CMS',
      slug: 'getting-started-react-cms',
    },
    replies: [],
    replies_count: 0,
  },
  {
    id: '3',
    post_id: '2',
    parent_id: null,
    author_name: 'Bob Wilson',
    author_email: 'bob@example.com',
    author_url: null,
    content: 'This is spam content with promotional links...',
    status: 'spam',
    created_at: '2024-01-17T14:45:00Z',
    updated_at: '2024-01-17T14:45:00Z',
    post: {
      id: '2',
      title: 'Advanced Media Management',
      slug: 'advanced-media-management',
    },
    replies: [],
    replies_count: 0,
  },
];

export const mockTenants = [
  {
    id: '1',
    name: 'Tech News Hub',
    domain: 'technews.com',
    subdomain: 'technews',
    status: 'active',
    settings: {
      theme: 'default',
      logo_url: '/images/logo/logo-01.png',
      primary_color: '#3B82F6',
      timezone: 'UTC',
      language: 'en',
      currency: 'USD',
    },
    subscription: {
      plan: 'Pro',
      status: 'active',
      expires_at: '2024-12-31T23:59:59Z',
    },
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-15T10:00:00Z',
    users_count: 15,
    posts_count: 234,
  },
  {
    id: '2',
    name: 'Fashion Magazine',
    domain: 'fashionmag.com',
    subdomain: 'fashion',
    status: 'active',
    settings: {
      theme: 'minimal',
      logo_url: '/images/logo/logo-02.png',
      primary_color: '#EC4899',
      timezone: 'America/New_York',
      language: 'en',
      currency: 'USD',
    },
    subscription: {
      plan: 'Enterprise',
      status: 'active',
      expires_at: '2024-12-31T23:59:59Z',
    },
    created_at: '2024-01-05T00:00:00Z',
    updated_at: '2024-01-16T14:30:00Z',
    users_count: 8,
    posts_count: 156,
  },
  {
    id: '3',
    name: 'Local News',
    domain: 'localnews.com',
    subdomain: 'local',
    status: 'inactive',
    settings: {
      theme: 'corporate',
      logo_url: null,
      primary_color: '#059669',
      timezone: 'Europe/London',
      language: 'en',
      currency: 'GBP',
    },
    subscription: {
      plan: 'Basic',
      status: 'expired',
      expires_at: '2024-01-15T23:59:59Z',
    },
    created_at: '2023-12-01T00:00:00Z',
    updated_at: '2024-01-15T00:00:00Z',
    users_count: 3,
    posts_count: 45,
  },
];

export const mockUser = {
  id: '1',
  name: 'Admin User',
  email: 'admin@example.com',
  role: 'super_admin',
  tenant_ids: ['1', '2', '3'],
  current_tenant_id: '1',
  created_at: '2024-01-01T00:00:00Z',
};

// Mock API responses
export const createMockResponse = (data: any, total?: number) => {
  return Promise.resolve({
    data: {
      data: data,
      total: total || data.length,
      page: 1,
      limit: 20,
      pages: total ? Math.ceil(total / 20) : Math.ceil(data.length / 20),
    },
  });
};

export const createMockSingleResponse = (data: any) => {
  return Promise.resolve({
    data: data,
  });
};
